# Generated by Django 3.0.3 on 2020-02-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('currentConfirmedCount', models.CharField(max_length=20)),
                ('confirmedCount', models.CharField(max_length=20)),
                ('suspectedCount', models.CharField(max_length=20)),
                ('curedCount', models.CharField(max_length=20)),
                ('deadCount', models.CharField(max_length=20)),
                ('locationId', models.CharField(max_length=20)),
                ('cityEnglishName', models.CharField(max_length=50)),
                ('provinceName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.CharField(max_length=20)),
                ('continentName', models.CharField(max_length=20)),
                ('continentEnglishName', models.CharField(max_length=20)),
                ('countryName', models.CharField(max_length=20)),
                ('countryEnglishName', models.CharField(max_length=20)),
                ('provinceName', models.CharField(max_length=20)),
                ('provinceShortName', models.CharField(max_length=20)),
                ('provinceEnglishName', models.CharField(max_length=20)),
                ('currentConfirmedCount', models.CharField(max_length=20)),
                ('confirmedCount', models.CharField(max_length=20)),
                ('suspectedCount', models.CharField(max_length=20)),
                ('curedCount', models.CharField(max_length=20)),
                ('deadCount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=2000)),
                ('infoSource', models.CharField(max_length=40)),
                ('sourceUrl', models.CharField(max_length=100)),
                ('pubDate', models.CharField(max_length=40)),
                ('provinceName', models.CharField(max_length=20)),
                ('provinceId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='overall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentConfirmedCount', models.CharField(max_length=20)),
                ('confirmedCount', models.CharField(max_length=20)),
                ('suspectedCount', models.CharField(max_length=20)),
                ('curedCount', models.CharField(max_length=20)),
                ('deadCount', models.CharField(max_length=20)),
                ('seriousCount', models.CharField(max_length=20)),
                ('seriousConfirmedIncr', models.CharField(max_length=20)),
                ('confirmedIncr', models.CharField(max_length=20)),
                ('suspectedIncr', models.CharField(max_length=20)),
                ('curedIncr', models.CharField(max_length=20)),
                ('deadIncr', models.CharField(max_length=20)),
                ('seriousIncr', models.CharField(max_length=20)),
                ('generalRemark', models.CharField(max_length=200)),
                ('abroadRemark', models.CharField(max_length=20)),
                ('remark1', models.CharField(max_length=200)),
                ('remark2', models.CharField(max_length=200)),
                ('remark3', models.CharField(max_length=200)),
                ('remark4', models.CharField(max_length=200)),
                ('remark5', models.CharField(max_length=200)),
                ('note1', models.CharField(max_length=200)),
                ('note2', models.CharField(max_length=200)),
                ('updatetime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rumors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mainSummary', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('rumorType', models.CharField(max_length=20)),
                ('sourceUrl', models.CharField(max_length=20)),
            ],
        ),
    ]
