# Generated by Django 3.0.3 on 2020-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virus_s', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rumors',
            old_name='sourceUrl',
            new_name='rumorsid',
        ),
        migrations.AddField(
            model_name='overall',
            name='note3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
