# Generated by Django 3.0.3 on 2020-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virus_s', '0004_auto_20200220_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacity',
            name='cityEnglishName',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='areacity',
            name='provinceName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='countryEnglishName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='countryName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='provinceEnglishName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='provinceName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='provinceShortName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='abroadRemark',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='confirmedCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='confirmedIncr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='curedCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='curedIncr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='currentConfirmedCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='currentConfirmedIncr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='deadCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='deadIncr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='generalRemark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='note1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='note2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='note3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='remark1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='remark2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='remark3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='remark4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='remark5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='seriousCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='seriousIncr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='suspectedCount',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overall',
            name='suspectedIncr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
