# Generated by Django 3.0.3 on 2020-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virus_s', '0005_auto_20200220_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='wuhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('currentConfirmedCount', models.CharField(max_length=20)),
                ('confirmedCount', models.CharField(max_length=20)),
                ('suspectedCount', models.CharField(max_length=20)),
                ('curedCount', models.CharField(max_length=20)),
                ('deadCount', models.CharField(max_length=20)),
                ('locationId', models.CharField(max_length=20)),
                ('cityEnglishName', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
