# Generated by Django 3.0.3 on 2020-02-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virus_s', '0006_wuhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wuhan',
            name='updateTime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
