# Generated by Django 3.0.3 on 2020-02-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virus_s', '0007_wuhan_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='hubei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=200, null=True)),
                ('provinceShortName', models.CharField(max_length=200, null=True)),
                ('provinceEnglishName', models.CharField(max_length=200, null=True)),
                ('currentConfirmedCount', models.CharField(max_length=20)),
                ('confirmedCount', models.CharField(max_length=20)),
                ('suspectedCount', models.CharField(max_length=20)),
                ('curedCount', models.CharField(max_length=20)),
                ('deadCount', models.CharField(max_length=20)),
                ('updatetime', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='wuhan',
            name='updateTime',
            field=models.CharField(max_length=100),
        ),
    ]
