# Generated by Django 3.0.3 on 2020-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Virus_s', '0008_auto_20200221_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='infoSource',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='provinceId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='provinceName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pubDate',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='sourceUrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
