from django.db import models

# Create your models here.
class overall(models.Model):
    currentConfirmedCount = models.CharField(max_length=20,null=True)
    confirmedCount  = models.CharField(max_length=20,null=True)
    suspectedCount = models.CharField(max_length=20,null=True)
    curedCount = models.CharField(max_length=20,null=True)
    deadCount = models.CharField(max_length=20,null=True)
    seriousCount = models.CharField(max_length=20,null=True)
    currentConfirmedIncr = models.CharField(max_length=20,null=True)
    confirmedIncr = models.CharField(max_length=20,null=True)
    suspectedIncr = models.CharField(max_length=20,null=True)
    curedIncr = models.CharField(max_length=20,null=True)
    deadIncr = models.CharField(max_length=20,null=True)
    seriousIncr = models.CharField(max_length=20,null=True)
    generalRemark = models.CharField(max_length=200,null=True)
    abroadRemark = models.CharField(max_length=20,null=True)
    remark1 = models.CharField(max_length=200,null=True)
    remark2 = models.CharField(max_length=200,null=True)
    remark3 = models.CharField(max_length=200,null=True)
    remark4 = models.CharField(max_length=200,null=True)
    remark5 = models.CharField(max_length=200,null=True)
    note1 = models.CharField(max_length=200,null=True)
    note2 = models.CharField(max_length=200,null=True)
    note3 = models.CharField(max_length=200,null=True)
    updatetime = models.CharField(max_length=100)

class City(models.Model):
    locationId= models.CharField(max_length=20)
    continentName= models.CharField(max_length=200)
    continentEnglishName= models.CharField(max_length=200)
    countryName= models.CharField(max_length=200,null=True)
    countryEnglishName= models.CharField(max_length=200,null=True)
    provinceName= models.CharField(max_length=200,null=True)
    provinceShortName= models.CharField(max_length=200,null=True)
    provinceEnglishName= models.CharField(max_length=200,null=True)
    currentConfirmedCount= models.CharField(max_length=20)
    confirmedCount= models.CharField(max_length=20)
    suspectedCount= models.CharField(max_length=20)
    curedCount= models.CharField(max_length=20)
    deadCount= models.CharField(max_length=20)

class AreaCity(models.Model):
    cityName=models.CharField(max_length=100)
    currentConfirmedCount=models.CharField(max_length=20)
    confirmedCount=models.CharField(max_length=20)
    suspectedCount=models.CharField(max_length=20)
    curedCount=models.CharField(max_length=20)
    deadCount=models.CharField(max_length=20)
    locationId=models.CharField(max_length=20)
    cityEnglishName=models.CharField(max_length=500,null=True)
    provinceName=models.CharField(max_length=100,null=True)

class news(models.Model):
    title=models.CharField(max_length=200)
    summary=models.CharField(max_length=2000,null=True)
    infoSource=models.CharField(max_length=40,null = True)
    sourceUrl=models.CharField(max_length=1000,null=True)
    pubDate=models.CharField(max_length=40,null=True)
    provinceName=models.CharField(max_length=200,null=True)
    provinceId=models.CharField(max_length=20,null=True)

class rumors(models.Model):
    rumorsid=models.CharField(max_length=20)
    title=models.CharField(max_length=1000)
    mainSummary=models.CharField(max_length=1000)
    body=models.CharField(max_length=2000)
    rumorType=models.CharField(max_length=20)

class wuhan(models.Model):
    cityName = models.CharField(max_length=100)
    currentConfirmedCount = models.CharField(max_length=20)
    confirmedCount = models.CharField(max_length=20)
    suspectedCount = models.CharField(max_length=20)
    curedCount = models.CharField(max_length=20)
    deadCount = models.CharField(max_length=20)
    locationId = models.CharField(max_length=20)
    cityEnglishName = models.CharField(max_length=500, null=True)
    updateTime = models.CharField(max_length=100)

class hubei(models.Model):
    provinceName = models.CharField(max_length=200, null=True)
    provinceShortName = models.CharField(max_length=200, null=True)
    provinceEnglishName = models.CharField(max_length=200, null=True)
    currentConfirmedCount = models.CharField(max_length=20)
    confirmedCount = models.CharField(max_length=20)
    suspectedCount = models.CharField(max_length=20)
    curedCount = models.CharField(max_length=20)
    deadCount = models.CharField(max_length=20)
    updatetime = models.CharField(max_length=100)
